default_rdf_namespaces = {
    'dc': 'http://purl.org/dc/elements/1.1/',
    'ro': 'http://purl.org/wf4ever/ro#',
    'dct': 'http://purl.org/dc/terms/',
    'deo': 'http://purl.org/spar/deo/',
    'org': 'http://www.w3.org/ns/org# ',
    'owl': 'http://www.w3.org/2002/07/owl#',
    'pso': 'http://purl.org/spar/pso/',
    'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
    'xml': 'http://www.w3.org/XML/1998/namespace',
    'xsd': 'http://www.w3.org/2001/XMLSchema#',
    'adms': 'http://www.w3.org/ns/adms#',
    'asio': 'http://purl.org/hercules/asio/core#',
    'ex': 'http://www.purl.org/hercules/asio/core#',
    'bibo': 'http://purl.org/ontology/bibo/',
    'dcat': 'http://www.w3.org/ns/dcat#',
    'doco': 'http://purl.org/spar/doco/',
    'foaf': 'http://xmlns.com/foaf/0.1/',
    'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
    'skos': 'http://www.w3.org/2004/02/skos/core#',
    'time': 'http://www.w3.org/2006/time#',
    'vivo': 'http://vivoweb.org/ontology/core#',
    'cerif': 'http://purl.org/cerif/',
    'fabio': 'http://purl.org/spar/fabio/',
    'frapo': 'http://purl.org/cerif/frapo#',
    'modules': 'http://purl.org/hercules/asio/modules#',
    'semcerif': 'http://eurocris.org/ontology/semcerif#',
    'timezone': 'http://www.w3.org/2006/timezone#',
    'humantechreadiness': 'http://sweetontology.net/humanTechReadiness#',
    'vcard': 'http://www.w3.org/2001/vcard-rdf/3.0#',
    'void': 'http://rdfs.org/ns/void#',
    'xf': 'http://www.w3.org/2004/07/xpath-functions',
    'math': 'http://www.w3.org/2000/10/swap/math#',
    'mf': 'http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#'
}
