codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "90..100"

  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 5%
